#!/bin/sh

# https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding.html
if [ -n "$SSH_CLIENT" ]    && [ ! -S ~/.ssh/ssh_auth_sock ] && \
   [ -n "$SSH_AUTH_SOCK" ] && [ -S "$SSH_AUTH_SOCK" ]; then
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi

if read -r proto cookie && [ -n "$DISPLAY" ]; then
  if [ `echo "$DISPLAY" | cut -c1-10` = "localhost:" ]; then
    # X11UseLocalhost=yes
    echo "add unix:$(echo "$DISPLAY" | cut -c11-) $proto $cookie"
  else
    # X11UseLocalhost=no
    echo "add $DISPLAY $proto $cookie"
  fi | xauth -q -
fi
