Opt.termguicolors = true
Opt.background    = "dark"
Cmd "colorscheme solarized"

local function set_colour(group, part, colour)
  Cmd(string.format("highlight %s %s=%s", group, part, colour))
end

function _G.set_buffer_colours()
  set_colour("Normal",                               "guifg", Col_normal )
  set_colour("SpecialKey",                           "guibg", Col_base03 )
  set_colour("SpellBad",                             "guibg", Col_violet )
  set_colour("SpellBad",                             "guifg", Col_base03 )
  set_colour("SpellBad",                             "gui",   Col_none   )
  set_colour("SpellCap",                             "guibg", Col_blue   )
  set_colour("SpellCap",                             "guifg", Col_base03 )
  set_colour("SpellCap",                             "gui",   Col_none   )
  set_colour("SpellRare",                            "guibg", Col_yellow )
  set_colour("SpellRare",                            "guifg", Col_base03 )
  set_colour("SpellRare",                            "gui",   Col_none   )
  set_colour("SpellLocal",                           "guibg", Col_green  )
  set_colour("SpellLocal",                           "guifg", Col_base03 )
  set_colour("SpellLocal",                           "gui",   Col_none   )
  set_colour("LineNr",                               "guibg", Col_base03 )
  set_colour("ColorColumn",                          "guibg", Col_base06 )
  set_colour("CursorLine",                           "guibg", Col_base02 )
  set_colour("CursorColumn",                         "guibg", Col_base02 )
  set_colour("CursorLineNr",                         "guibg", Col_base03 )
  set_colour("DiffAdd",                              "guibg", Col_base03 )
  set_colour("DiffAdd",                              "guifg", Col_rgreen )
  set_colour("DiffChange",                           "guibg", Col_base03 )
  set_colour("DiffDelete",                           "guibg", Col_base03 )
  set_colour("DiffAdded",                            "guifg", Col_rgreen )
  set_colour("Search",                               "guibg", Col_violet )
  set_colour("Search",                               "guifg", Col_base03 )
  set_colour("Search",                               "gui",   Col_none   )
  set_colour("TabLineSel",                           "guibg", Col_base03 )
  set_colour("TabLineSel",                           "guifg", Col_violet )
  set_colour("Folded",                               "gui",   Col_none   )
  set_colour("MatchParen",                           "guibg", Col_base00 )
  set_colour("MatchParen",                           "guifg", Col_none   )
  set_colour("MatchParenCur",                        "guibg", Col_base02 )
  set_colour("MatchParenCur",                        "guifg", Col_none   )
  set_colour("NormalFloat",                          "guibg", Col_base04 )
  set_colour("Pmenu",                                "guifg", Col_dred   )
  set_colour("Pmenu",                                "guibg", Col_base2  )
  set_colour("PmenuSel",                             "guifg", Col_dorange)
  set_colour("PmenuSel",                             "guibg", Col_base2  )

  set_colour("GitSignsAdd",                          "guibg", Col_base03 )
  set_colour("GitSignsAdd",                          "guifg", Col_rgreen )
  set_colour("GitSignsChange",                       "guibg", Col_base03 )
  set_colour("GitSignsChange",                       "guifg", Col_yellow )
  set_colour("GitSignsDelete",                       "guibg", Col_base03 )
  set_colour("GitSignsDelete",                       "guifg", Col_red    )

  set_colour("GitSignsCurrentLineBlame",             "guifg", Col_base05 )

  set_colour("IndentOdd",                            "guibg", Col_none   )
  set_colour("IndentEven",                           "guibg", Col_base02 )

  set_colour("GoDiagnosticError",                    "guibg", Col_none   )
  set_colour("GoDiagnosticError",                    "guifg", Col_red    )

  set_colour("LspDiagnosticsDefaultError",           "guifg", Col_red    )
  set_colour("LspDiagnosticsVirtualTextError",       "guifg", Col_dorange)
  set_colour("LspDiagnosticsVirtualTextWarning",     "guifg", Col_dyellow)
  set_colour("LspDiagnosticsVirtualTextInformation", "guifg", Col_dcyan  )
  set_colour("LspDiagnosticsVirtualTextHint",        "guifg", Col_dblue  )
  set_colour("LspDiagnosticsSignError",              "guifg", Col_orange )
  set_colour("LspDiagnosticsSignWarning",            "guifg", Col_yellow )
  set_colour("LspDiagnosticsSignInformation",        "guifg", Col_cyan   )
  set_colour("LspDiagnosticsSignHint",               "guifg", Col_blue   )

  set_colour("ALEVirtualTextError",                  "guifg", Col_dorange)
  set_colour("ALEVirtualTextWrning",                 "guifg", Col_dyellow)
  set_colour("ALEVirtualTextInfo",                   "guifg", Col_dcyan  )

  set_colour("ScrollView",                           "guibg", Col_blue   )
end
