G.mapleader = ","

Map("n", "<S-F1>",     ":q<cr>",                              Defmap)
Map("i", "<F5>",       "[",                                   Defmap)
Map("n", "r<F5>",      "r[",                                  Defmap)
Map("n", "<F6>",       ":cprevious<cr>",                      Defmap)
Map("n", "<S-F6>",     ":lprevious<cr>",                      Defmap)
Map("i", "<F6>",       "]",                                   Defmap)
Map("n", "r<F6>",      "r]",                                  Defmap)
Map("n", "<F7>",       ":cnext<cr>",                          Defmap)
Map("n", "<S-F7>",     ":lnext<cr>",                          Defmap)
Map("i", "<F7>",       "{",                                   Defmap)
Map("n", "r<F7>",      "r{",                                  Defmap)
Map("i", "<F8>",       "}",                                   Defmap)
Map("n", "r<F8>",      "r}",                                  Defmap)
Map("n", "<F9>",       "<cmd>cclose<bar>lclose<bar>only<cr>", Defmap)
Map("i", "<F9>",       "|",                                   Defmap)
Map("n", "r<F9>",      "r|",                                  Defmap)
Map("i", "<F10>",      "~",                                   Defmap)
Map("n", "r<F10>",     "r~",                                  Defmap)
Map("n", "<F12>",      "",                                  Defmap)
Map("n", "<PageUp>",   "0",                                 Defmap)
Map("n", "<PageDown>", "0",                                 Defmap)

Map("n", "<F13>", "<S-F1>",  {})
Map("n", "<F14>", "<S-F2>",  {})
Map("n", "<F15>", "<S-F3>",  {})
Map("n", "<F16>", "<S-F4>",  {})
Map("n", "<F17>", "<S-F5>",  {})
Map("n", "<F18>", "<S-F6>",  {})
Map("n", "<F19>", "<S-F7>",  {})
Map("n", "<F20>", "<S-F8>",  {})
Map("n", "<F21>", "<S-F9>",  {})
Map("n", "<F22>", "<S-F10>", {})
Map("n", "<F23>", "<S-F11>", {})
Map("n", "<F24>", "<S-F12>", {})

Map("n", "<F25>", "<C-F1>",  {})
Map("n", "<F26>", "<C-F2>",  {})
Map("n", "<F27>", "<C-F3>",  {})
Map("n", "<F28>", "<C-F4>",  {})
Map("n", "<F29>", "<C-F5>",  {})
Map("n", "<F30>", "<C-F6>",  {})
Map("n", "<F31>", "<C-F7>",  {})
Map("n", "<F32>", "<C-F8>",  {})
Map("n", "<F33>", "<C-F9>",  {})
Map("n", "<F34>", "<C-F10>", {})
Map("n", "<F35>", "<C-F11>", {})
Map("n", "<F36>", "<C-F12>", {})

Map("n", "<F37>", "<M-F1>",  {})
-- not working with neovim
Map("n", "<F38>", "<M-F2>",  {})
Map("n", "<F39>", "<M-F3>",  {})
Map("n", "<F40>", "<M-F4>",  {})
Map("n", "<F41>", "<M-F5>",  {})
Map("n", "<F42>", "<M-F6>",  {})
Map("n", "<F43>", "<M-F7>",  {})
Map("n", "<F44>", "<M-F8>",  {})
Map("n", "<F45>", "<M-F9>",  {})
Map("n", "<F46>", "<M-F10>", {})
Map("n", "<F47>", "<M-F11>", {})
Map("n", "<F48>", "<M-F12>", {})

Map("n", "<leader>.",  [[<cmd>lua require"telescope.builtin".find_files({ hidden = true })<cr>]], Defmap)
Map("n", "<leader> ",  [[<cmd>lua require"telescope.builtin".oldfiles()<cr>]],                    Defmap)
Map("n", "<leader>m",  [[<cmd>lua require"telescope.builtin".git_status()<cr>]],                  Defmap)
Map("n", "<leader>fb", [[<cmd>lua require"telescope.builtin".buffers()<cr>]],                     Defmap)
Map("n", "<leader>ff", [[<cmd>lua require"telescope.builtin".builtin()<cr>]],                     Defmap)
Map("n", "<leader>fg", [[<cmd>lua require"telescope.builtin".live_grep()<cr>]],                   Defmap)
Map("n", "<leader>fh", [[<cmd>lua require"telescope.builtin".help_tags()<cr>]],                   Defmap)
Map("n", "<leader>fs", [[<cmd>lua require"telescope.builtin".grep_string()<cr>]],                 Defmap)
Map("n", "<leader>fl", [[<cmd>lua require"telescope.builtin".current_buffer_fuzzy_find()<cr>]],   Defmap)
Map("n", "<leader>fa", [[<cmd>lua require"telescope.builtin".lsp_code_actions()<cr>]],            Defmap)
Map("n", "<leader>fd", [[<cmd>lua require"telescope.builtin".lsp_definitions()<cr>]],             Defmap)

Map("n", "<leader>gg", [[<cmd>tab Git commit<cr>]], Defmap)

Map("n", "ga",      "<Plug>(EasyAlign)", {})
Map("x", "ga",      "<Plug>(EasyAlign)", {})
Map("v", "<Enter>", "<Plug>(EasyAlign)", {})

Map("n", "<leader>qq", [[cs'"]], {})
Map("n", "<leader>qQ", [[cs"']], {})

-- map("n", "<leader>l" [[<cmd>let @/ = ""<bar> :call UncolorAllWords()<cr>]], Defmap)

Cmd([[
  nnoremap <silent> <leader>l :let @/ = ""<bar> :call UncolorAllWords()<cr>
]])
