---
# model
# anthropic-api-key:

# cache
cache-prompts: true

# output
dark-mode: true
code-theme: solarized-dark

# git
auto-commits: false
dirty-commits: false
show-diffs: true

# analytics
analytics-disable: true

# other
vim: false
multiline: false

read:
  - ~/conventions.md
  - ~/.claude/CLAUDE.md
  - CLAUDE.md
