#!/bin/zsh

# run this script to configure the basics of the system
# . ./SETUP

sudo aptitude install build-essential

ln -bs g/base/{utils,.abcde.conf,.gitconfig,.profile,.urlview} ~
ln -bs g/base/{.vimrc,.Xdefaults,.vim,.nvim,.tmux.conf,.tigrc,.doitrc} ~
[[ -d ~/.config ]] || mkdir ~/.config
ln -bs ~/g/base/.config/* ~/.config
( cd ~ && ln -bs g/base/.zshrc* g/base/.zshenv . )

[[ -d ~/.zplug ]] || curl -sL --proto-redir -all,https \
    https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

echo "Start tmux and then run full_build"

exit

# For vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim


# for cp1

sudo aptitude install python3-dev
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user


Set up theme with https://github.com/ferdi265/numix-solarized-gtk-theme


cd ~
mkdir -p ~/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf
