#!/bin/zsh

# run this script to configure the basics of the system
# . ./SETUP

ln -s g/base/{dircolours,utils,.abcde.conf,.gitconfig} ~
ln -s g/base/{.notion,.vimrc,.Xdefaults,.vim,.nvim,.tmux.conf} ~
[[ -d ~/.config ]] || mkdir ~/.config
ln -s ~/g/base/.config/* ~/.config
( cd ~ && ln -s g/base/.zshrc.* . )

# wget --no-check-certificate http://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh
# ln -s ~/g/base/zsh/pjcj.zsh-theme ~/.oh-my-zsh/themes
# perl -pi -e 's/robbyrussell/pjcj/' ~/.zshrc
# perl -pi -e 's/git/colored-man cpanm zsh-syntax-highlighting/' ~/.zshrc
# echo source ~/g/base/zsh/pjcj.zsh >> ~/.zshrc
# cd ~/.oh-my-zsh/custom
# mkdir plugins
# cd plugins
# git clone git://github.com/zsh-users/zsh-syntax-highlighting.git

curl -fLo ~/.zplug/zplug --create-dirs https://git.io/zplug

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

exit

# TODO - do we need tmuxinator now?
# sudo gem install tmuxinator

# if necessary
# either
# sudo aptitude install python-pip
# or
# wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
# python get-pip.py

pip install --upgrade --user git+git://github.com/Lokaltog/powerline

# if necessary
# sudo aptitude install libncurses-dev
# cd ~/g/sw/build
# wget https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz
# wget https://sourceforge.net/projects/levent/files/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz
# ./configure --prefix=~/g/sw
# wget http://downloads.sourceforge.net/tmux/tmux-2.0.tar.gz
# export LIBEVENT_CFLAGS="-I/home/pjcj/g/sw/include"
# export LIBEVENT_LIBS="-L/home/pjcj/g/sw/lib -Wl,-rpath=/home/pjcj/g/sw/lib -levent"
# ./configure --prefix=~/g/sw

cd ~
mkdir -p ~/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf

aptitude install libxcb-util0-dev libxcb-keysyms1-dev libxcb-xinerama0-dev \
                 libxcb-randr0-dev libxcb-icccm4-dev libxcb-ewmh1-dev
aptitude install xcb libxcb-util0-dev libxcb-ewmh-dev libxcb-randr0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-xinerama0-dev libxcb-ewmh2
git clone https://github.com/baskerville/sxhkd.git
make install PREFIX=~/g/sw
git clone https://github.com/baskerville/bspwm.git
make install PREFIX=~/g/sw

git clone  https://github.com/Lokaltog/candybar.git
aptitude install libgtk-3-dev libgtk-3-0 webkit-image-gtk libwebkitgtk-3.0-dev \
                 libdbusmenu-gtk3-dev libjansson-dev
./waf configure --prefix=~/g/sw
./waf install --prefix=~/g/sw

sudo ln -s ~base/bspwm.desktop /usr/share/xsessions
sudo ln -s ~/g/sw/bin/{bspwm-session,sxhkd,bspc,bspwm} /usr/local/bin
