#!/bin/zsh

# run this script to configure the basics of the system
# . ./SETUP

ln -s g/base/{dircolours,utils,.abcde.conf,.gitconfig,.profile,.urlview} ~
ln -s g/base/{.vimrc,.Xdefaults,.vim,.nvim,.tmux.conf,.tigrc} ~
[[ -d ~/.config ]] || mkdir ~/.config
ln -s ~/g/base/.config/* ~/.config
( cd ~ && ln -s g/base/.zshrc* . )
( cd ~ && ln -s g/base/.sxhkdrc* . )
sudo ln -s ~/g/base/bspwm.desktop /usr/share/xsessions
sudo ln -s ~/g/base/bspwm-session /usr/local/bin

# mkdir ~/.mozilla/firefox/*.default*/chrome
# cp ~/g/base/userContent.css ~/.mozilla/firefox/*.default*/chrome

curl -sL --proto-redir -all,https \
    https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Start tmux and then run build_all"

exit

# For OSX

mkdir ~/g/tmp
cd ~/g/tmp
brew install wget npm autoconf cmake pkgconfig automake libtool gettext ctags fzf rg
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
PATH=~/Library/Python/2.7/bin:$PATH
PATH=~/go/bin:$PATH


# for cp1

sudo aptitude install python3-dev
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user


Set up theme with https://github.com/ferdi265/numix-solarized-gtk-theme


cd ~
mkdir -p ~/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf
