#!/usr/bin/env bash

set -eEuo pipefail
shopt -s inherit_errexit 2>/dev/null || true

# Toggle tmux mouse mode on/off
# Used by tmux binding C-a y

main() {
  local to
  if [[ "$(tmux show-options -g mouse)" == *off ]]; then
    to=on
  else
    to=off
  fi

  echo "turning mouse $to"
  tmux set -g mouse "$to" >/dev/null
}

main "$@"
