[files]
  extend-exclude = [ ".codespell" ]
  ignore-hidden = false

[default.extend-words]

[default.extend-identifiers]

[default]

extend-ignore-words-re = [
]

extend-ignore-identifiers-re = [
]

extend-ignore-re = [
  '"[^"]+"\n\n__END__\n\n',     # quotes
  '::ProhibitMultipleWiths\b',  # perl critic
]
