theme = "solarized-dark"

[themes.solarized-dark]
base    = "dark"
bg      = "#001920"
surface = "#00090c"
overlay = "#0e3c49"
fg      = "#fff9c7"
muted   = "#93a1a1"
border  = "#839496"
accent  = "#9fcff2"
red     = "#ff8784"
orange  = "#f0a63f"
yellow  = "#fff179"
green   = "#98e59d"
cyan    = "#a9eae5"
blue    = "#9fcff2"
purple  = "#c0c3ef"
magenta = "#ffdc79"
