# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to
# validate your config. If you encounter any issues, please make an issue at
# https://github.com/yazi-rs/schemas.

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 3, 3 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "size_and_mtime"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 24000
max_height      = 24000
cache_dir       = ""
image_delay     = 0
image_filter    = "lanczos3"
image_quality   = 90
sixel_fraction  = 15
ueberzug_scale  = 2
ueberzug_offset = [ 0, 0, 0, 0 ]


[tasks]
micro_workers    = 10
macro_workers    = 10
bizarre_retry    = 3
image_alloc      = 4294967295  # max, about 4GB
image_bound      = [ 0, 0 ]
suppress_preload = false
