#!/usr/bin/env bash

log=/tmp/ale_perl.log
date >> $log
echo "$@" >> $log

blib=
[[ -d blib ]] && blib=-Mblib

perl -X -c -Mwarnings -Ilib $blib "$@" 2>&1 | grep -v set_first_init_and_end \
    | tee -a $log
