#!/bin/sh

set -e

dir=$(basename "$(pwd)")
sw=$HOME/g/sw

configure() {
    [ -f ./configure ] || ./autogen.sh
    ./configure --prefix="$sw" "$@"
}

case "$dir" in
    urlview|htop)
        configure
        make check install
        ;;
    libevent)
        configure
        make install
        ;;
    neovim)
        make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$sw" \
             CMAKE_BUILD_TYPE=Release test install
        ;;
    st)
        sudo aptitude -y install fontconfig libfontconfig1-dev \
            libfreetype6 libfreetype6-dev libxft-dev
        make clean install
        ;;
    sxhkd|bspwm)
        sudo aptitude -y install libxcb-util0-dev libxcb-keysyms1-dev     \
            libxcb-xinerama0-dev libxcb-randr0-dev libxcb-icccm4-dev      \
            libxcb-ewmh1-dev install xcb libxcb-util0-dev libxcb-ewmh-dev \
            libxcb-randr0-dev libxcb-icccm4-dev libxcb-keysyms1-dev       \
            libxcb-xinerama0-dev libxcb-ewmh2
        make PREFIX="$sw" all install
        ;;
    xdotool)
        make PREFIX="$sw" all test install
        sudo ldconfig
        ;;
    zsh)
        configure --enable-pcre
        make check
        make install || echo make install expected to fail
        ;;
    tmux)
        export LIBEVENT_CFLAGS="-I$sw/include"
        export LIBEVENT_LIBS="-L$sw/lib -Wl,-rpath=$sw/lib -levent"
        configure
        make check install
        ;;
    zsh-git-prompt)
        stack setup
        stack build && stack install
        ;;
    shellcheck)
        cabal update && cabal install --prefix="$sw"
        ;;
    *)
        echo unknown directory "$dir"
        ;;
esac

echo "built $dir"
