#!/bin/sh

dist=$1
if [ "$dist" ]; then
    dir=$(ghq list -p | grep "$dist$")
    # echo "$dist", "$dir"
    if [ "$dir" ]; then
        cd "$dir" || exit 1
    fi
    # echo building "$dist"
fi

set -e

build="$dir"
if [ -z "$dir" ]; then
    if [ "$dist" ]; then
        build="$dist"
    else
        build=$(basename "$(pwd)")
    fi
fi
echo build "$build"

sw=$HOME/g/sw

configure() {
    [ -f ./configure ] || ./autogen.sh
    ./configure --prefix="$sw" "$@"
}

exit_unless_x() {
    if ! xset q > /dev/null 2>&1; then
        echo "not running under X, ignoring $build"
        exit
    fi
}

case "$build" in
    urlview)
        autoreconf -vfi
        configure
        make check install
        ;;
    htop)
        sudo aptitude -y install libncursesw5-dev
        configure
        make check install
        ;;
    libevent)
        exit_unless_x
        configure
        make install
        ;;
    neovim)
        sudo aptitude -y install \
            libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
        git clean -dxf
        make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$sw" \
             CMAKE_BUILD_TYPE=Release test install
        ;;
    st)
        exit_unless_x
        sudo aptitude -y install fontconfig libfontconfig1-dev \
            libfreetype6 libfreetype6-dev libxft-dev
        rm -f "$sw/bin/st" "$sw/bin/st2"
        for f in $(seq 10 20); do
            perl -pi -e "s/Inconsolata for Powerline:pixelsize=\K\d\d/$f/" \
                config.def.h
            make clean install
            mv "$sw/bin/st" "$sw/bin/st$f"
        done
        ln -s "$sw/bin/st${FONTSIZE:-14}" "$sw/bin/st"
        ln -s "$sw/bin/st${FONTSIZE2:-16}" "$sw/bin/st2"
        ;;
    sxhkd|bspwm)
        exit_unless_x
        sudo aptitude -y install libxcb-util0-dev libxcb-keysyms1-dev     \
            libxcb-xinerama0-dev libxcb-randr0-dev libxcb-icccm4-dev      \
            libxcb-ewmh1-dev xcb libxcb-util0-dev libxcb-ewmh-dev         \
            libxcb-randr0-dev libxcb-icccm4-dev libxcb-keysyms1-dev       \
            libxcb-xinerama0-dev libxcb-ewmh2                             \
            gnome-panel
        make PREFIX="$sw" all install
        ;;
    xdotool)
        exit_unless_x
        sudo aptitude -y install libxinerama-dev x11proto-xinerama-dev \
            libxkbcommon-dev
        make PREFIX="$sw" all test install
        sudo ldconfig
        ;;
    zsh)
        git checkout "$(git tag | grep -v dev | grep -v test | tail -1)"
        autoreconf -vfi
        configure --enable-pcre
        make
        make check
        make install || echo make install expected to fail - docs not built
        ;;
    tmux)
        export LIBEVENT_CFLAGS="-I$sw/include"
        export LIBEVENT_LIBS="-L$sw/lib -Wl,-rpath=$sw/lib -levent"
        configure
        make check install
        ;;
    zsh-git-prompt)
        stack setup
        stack build && stack install
        ;;
    shellcheck)
        cabal update && cabal install --prefix="$sw"
        ;;
    skype)
        exit_unless_x
        sudo dpkg --add-architecture i386
        sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
        sudo aptitude update && sudo aptitude -y install skype
        ;;
    ClipIt)
        exit_unless_x
        sudo aptitude -y install autopoint intltool
        ./autogen.sh
        configure
        make
        make install
        ;;
    PathPicker)
        target="$sw/bin/fpp"
        [ -e "$target" ] || ln -s "$(pwd)/fpp" "$target"
        ;;
    diff-so-fancy)
        cp -a diff-so-fancy third_party/diff-highlight/diff-highlight \
              third_party/ansi-reveal \
            "$sw/bin"
        dir="$sw/bin/libexec"
        mkdir -p "$dir"
        cp -a libexec/diff-so-fancy.pl "$dir"
        perl -pi -e 's/my \$ansi_color_regex = qr.*\K3/4/' "$dir/diff-so-fancy.pl"
        ;;
    tig)
        configure
        make test || echo "make test expected to fail - don't know why"
        make install
        ;;
    git)
        sudo aptitude -y install libcurl4-openssl-dev gettext
        git checkout "$(git tag | grep -v rc | tail -1)"
        make prefix="$sw" all install
        ;;
    caps2esc)
        exit_unless_x
        sudo aptitude -y install libudev-dev libevdev-dev
        gcc -std=gnu99 caps2esc.c -o caps2esc -I/usr/include/libevdev-1.0 -levdev -ludev
        cp caps2esc "$sw/bin"
        ;;
    rg)
        gh="https://github.com"
        tar=$(wget -O - -o /dev/null $gh/BurntSushi/ripgrep/releases | \
              grep x86_64-unknown-linux-musl.tar.gz | head -1 |        \
              perl -ne 'print $1 if /"(.*?)"/')
        url="$gh/$tar"
        wget -O /tmp/rg.tgz "$url"
        dir="/tmp/rg"
        (rm -rf $dir; mkdir -p $dir && chdir $dir && tar xvzf /tmp/rg.tgz)
        ls -alR $dir
        mv $dir/*/rg "$sw/bin"
        mv $dir/*/rg.1 "$sw/man/man1"
        ;;
    *)
        echo unknown directory "$dir"
        ;;
esac

echo "built $build"
