#!/bin/sh

# set -x

gobase() { cd ~/g/base || exit 1; }

gobase

ghq import -u < ghq.repos

while read -r repo; do
    sw=$(basename "$repo")
    dir=$(ghq list -p | grep "$sw")
    # echo $repo, $sw, $dir
    # cd "$dir" || exit 1
    cd "$dir"
    echo building "$sw"
    build
done < ghq.repos
