#!/bin/sh

if [ "$(uname)" = "FreeBSD" ] || command -v diff-so-fancy > /dev/null 2>&1; then
    diff-so-fancy
elif command -v delta > /dev/null 2>&1; then
    delta \
        --width="$(tput cols)"  \
        --plus-color="#022010"  \
        --minus-color="#300C10" \
        --file-style=underline  \
        --file-color=yellow     \
        --commit-style=box
else
    cat
fi
