#!/bin/bash

# usage: file_creation_dates [file ...] | sort

for file in $(git ls-files "$@")
do
    HASH=$(git rev-list HEAD "$file" | tail -n 1)
    DATE=$(git show -s --format="%ci" "$HASH" --)
    echo "$DATE $file"
done
