#!/usr/bin/env zsh

# set -x

gobase() { cd ~/g/base || exit 1; }

cd ~

if [ ! -e .tmux.conf ]; then
    [[ -e .profile ]] && ! [[ -e .profile.local ]] && mv .profile .profile.local
    ln -s g/base/{utils,.abcde.conf,.gitconfig,.gitignore_global,.profile} ~
    ln -s g/base/{.urlview,.vimrc,.Xdefaults,.vim,.nvim,.tmux.conf,.tigrc} ~
    [[ -d ~/.config ]] || mkdir ~/.config
    ln -s ~/g/base/.config/* ~/.config
    ( cd ~ && ln -s g/base/.zshrc* g/base/.zshenv . )
fi

[[ -e ~/.ssh/rc      ]] || ln -s ~/g/base/.ssh/rc ~/.ssh
[[ -e ~/.ssh/config  ]] || cp ~/g/base/.ssh/config ~/.ssh
[[ -d ~/.ssh/sockets ]] || mkdir -p ~/.ssh/sockets

gobase

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
source "$ZINIT_HOME/zinit.zsh"
zinit self-update
zinit update --parallel

curl -SL https://github.com/docker/cli/raw/master/contrib/completion/zsh/_docker \
    >| ~/g/base/zsh/functions/_docker
curl -SL https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose \
    >| ~/g/base/zsh/functions/_docker-compose
curl -SL https://raw.githubusercontent.com/docker/machine/master/contrib/completion/zsh/_docker-machine \
    >| ~/g/base/zsh/functions/_docker-machine
curl -SL https://raw.githubusercontent.com/perlpunk/shell-completions/master/zsh/_dzil \
    >| ~/g/base/zsh/functions/_dzil
if [[ "$(uname)" == Darwin ]]; then
    curl https://raw.githubusercontent.com/zsh-users/zsh/master/Completion/Unix/Command/_git \
        >| ~/g/base/zsh/functions/_git
fi
rm -f ~/.zcompdump; autoload -Uz compinit && compinit -i

LOCALCHECKOUT=~/.tmux/plugins/tpm
if [ ! -d $LOCALCHECKOUT ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
    pushd $LOCALCHECKOUT
    git pull origin master
    popd
fi

~/.tmux/plugins/tpm/bin/install_plugins
~/.tmux/plugins/tpm/bin/update_plugins all
~/.tmux/plugins/tpm/bin/clean_plugins

bat cache --clear
bat cache --build

mkdir -p ~/.local/share/nvim/backup

if [[ "$(uname)" == Darwin ]]; then
    if which brew >&/dev/null; then
        brew update
        brew upgrade
        brew upgrade --cask
        brew bundle dump --file=Brewfile --force
    else
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew bundle install --file=Brewfile
    fi

    fzfcomp=/usr/local/opt/fzf/shell/completion.zsh
    if ! grep -q "emulate -L zsh" $fzfcomp; then
        perl -pi -e 's/fzf-completion\(\) \{\K/\n  emulate -L zsh/' \
            $fzfcomp
    fi

    cargo install devicon-lookup

    pip3=pip3
elif [[ "$(uname)" == FreeBSD ]]; then
    sudo pkg install          \
        base64                \
        bat                   \
        diff-so-fancy         \
        fd-find               \
        fzf                   \
        git-delta             \
        highlight             \
        multitail             \
        neovim                \
        node                  \
        www/npm               \
        pigz                  \
        pixz                  \
        py39-pip              \
        py39-powerline-status \
        py39-ranger           \
        ripgrep               \
        rust                  \
        thefuck               \
        tig                   \
        universal-ctags       \
        wget                  \
        yarn                  \
        zsh

    sudo pkg upgrade
    pip3=pip
else
    sudo locale-gen en_GB.UTF-8 en_US.UTF-8
    sudo update-locale

    sudo apt-get autoremove --purge
    sudo apt-get clean
    sudo aptitude update
    sudo aptitude full-upgrade

    if [[ -n $WSL_DISTRO_NAME ]]; then
        brewfile=Brewfile.wsl
    else
        brewfile=Brewfile.linux
    fi

    if which brew >&/dev/null; then
        brew update
        brew upgrade
        brew bundle dump --file=$brewfile --force
    else
        sudo apt-get install build-essential procps curl file git
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        brew bundle install --file=$brewfile
    fi

    pip3=pip3
    # sudo aptitude -y install golang python-pip python3-dev python3-pip cargo libncurses-dev libncursesw5-dev

    cargo install devicon-lookup

    # $pip3 install --upgrade --user pip

    # sudo gem install colorls
    # sudo gem update colorls
fi

$pip3 install --upgrade --user \
    thefuck \
    docker-compose \
    powerline-status \
    mdformat-gfm

if [[ "$EDITOR" == "nvimx" ]]; then
    $pip3 install --upgrade --user neovim pynvim
    $pip3 install --upgrade --user vim-vint proselint
    $pip3 install --upgrade --user git+git://github.com/powerline/powerline

    # denite
    $pip3 install --upgrade --user typing

    rm -f vimplug.lock
    $EDITOR -c PlugUpgrade                    -c qa
    $EDITOR -c PlugClean                      -c qa
    $EDITOR -c PlugInstall                    -c qa
    $EDITOR -c PlugUpdate                     -c qa
    $EDITOR -c PlugSnapshot\ vimplug.lock     -c qa

    yarn global add neovim
    $EDITOR -c "CocInstall coc-tag coc-emoji" -c qa
    $EDITOR -c "CocUpdateSync"                -c qa

    curl https://www.unicode.org/Public/UNIDATA/UnicodeData.txt > \
        ~/.local/share/nvim/site/unicode/UnicodeData.txt
fi

npm install -g fixjson

npm update -g

if [[ "$EDITOR" == "nvim" ]]; then
    $EDITOR -c "autocmd User PackerComplete quitall" -c "PackerSync"
    $EDITOR +TSUpdateSync +qall
    # $EDITOR --headless -c LspInstall\ --sync\ bashls
    # $EDITOR --headless -c LspInstall\ --sync\ cssls
    # $EDITOR --headless -c LspInstall\ --sync\ dockerls
    # $EDITOR --headless -c LspInstall\ --sync\ gopls
    # $EDITOR --headless -c LspInstall\ --sync\ html
    # $EDITOR --headless -c LspInstall\ --sync\ javascript
    # $EDITOR --headless -c LspInstall\ --sync\ jsonls
    # $EDITOR --headless -c LspInstall\ --sync\ sqlls
    # $EDITOR --headless -c LspInstall\ --sync\ sumneko_lua
    # $EDITOR --headless -c LspInstall\ --sync\ vimls
    # $EDITOR --headless -c LspInstall\ --sync\ vuels
    # $EDITOR --headless -c LspInstall\ --sync\ yamlls
    go install github.com/nametake/golangci-lint-langserver@latest
    go install github.com/client9/misspell/cmd/misspell@latest

    # $pip3 install --upgrade --user git+git://github.com/powerline/powerline
fi

# if [[ $(uname) == Linux ]]; then
    # gobase
    # brew install ghq
    # build_all
# fi
