#!/usr/bin/env zsh

# set -x

gobase() { cd ~/g/base || exit 1; }

gobase

source ~/.zplug/init.zsh
zplug clear
curl -SL https://github.com/docker/cli/raw/master/contrib/completion/zsh/_docker \
    >| ~/g/base/zsh/functions/_docker
curl -SL https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose \
    >| ~/g/base/zsh/functions/_docker-compose
curl -SL https://raw.githubusercontent.com/docker/machine/master/contrib/completion/zsh/_docker-machine \
    >| ~/g/base/zsh/functions/_docker-machine
rm -f ~/.zcompdump; autoload -Uz compinit && compinit -i

~/.tmux/plugins/tpm/bindings/clean_plugins
~/.tmux/plugins/tpm/bindings/install_plugins
~/.tmux/plugins/tpm/scripts/update_plugin_prompt_handler.sh all

# for neovim:
if [ "$ISOSX" ]; then
    brew update
    brew upgrade
    pip3=pip
else
    pip3=pip3
    # sudo aptitude -y install \
        # python-pip python-setuptools \
        # python3-pip python3-setuptools
    sudo aptitude -y install golang
fi
# sudo aptitude install python3-pip
# sudo pip2 install --upgrade neovim
$pip3 install --upgrade neovim
$pip3 install --upgrade --user vim-vint proselint
pip install --upgrade --user git+git://github.com/powerline/powerline

sudo gem install colorls
sudo gem update colorls

# urlwatch
$pip3 install --upgrade --user pyyaml minidb requests keyring chump urlwatch

# denite
$pip3 install --upgrade --user typing

$EDITOR -c PlugUpgrade -c qa
# $EDITOR -c PlugClean   -c qa
$EDITOR -c PlugInstall -c qa
$EDITOR -c PlugUpdate  -c qa

$EDITOR -c UnicodeDownload -c qa

gobase

command go get -u github.com/motemen/ghq

build_all
