#!/bin/sh

branch=$1
test -z "$branch" && echo "branch required" 1>&2 && exit 1

current_branch="$(git branch --show-current)"
git checkout -q "$(git rev-parse HEAD)"
git branch -f "$branch" "origin/$branch"
git checkout -q "$current_branch"
