#!/bin/bash

# first run git checkout $original
# then git commit --amend as required

err() { echo "Usage: $0 original new" 1>&2 && exit 1; }
original=$1
new=$2
test -z "$original" && err
test -z "$new" && err

git replace "$original" "$new"
git filter-branch -- --all
git replace -d "$original"
echo 'when everything looks good'
echo 'git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d'
