#!/bin/bash
set -euo pipefail

script=$(basename "$0")
srcdir=$(readlink -f "$(dirname "$0")")
readonly LOG_FILE="/tmp/$script.log"
_p() { l=$1; shift; echo "$l $script: $*" | tee -a "$LOG_FILE" >&2; }
pt() { _p "[TRACE]  " "$*";                                         }
pd() { _p "[DEBUG]  " "$*";                                         }
pi() { _p "[INFO]   " "$*";                                         }
pw() { _p "[WARNING]" "$*";                                         }
pe() { _p "[ERROR]  " "$*";                                         }
pf() { _p "[FATAL]  " "$*"; exit 1;                                 }

usage() {
    cat <<EOT
$script --help
$script --trace --verbose
$script --build_conf
$script
EOT
    exit 0
}

cleanup() {
    declare -r res=$?
    ((verbose)) && pi "Cleaning up"
    exit $res
}

build_conf() {
    dir=$(readlink -f "$srcdir/../.config/i3")
    conf="$dir/config"
    ((verbose)) && pi "building $conf"
    h=$(hostname)
    cp "$conf.base" "$conf"
    [ -e "$conf.$h" ] && cat "$conf.$h" >> "$conf"
}

PATH="$srcdir:$PATH"
verbose=0

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            shift
            ;;
        -t|--trace)
            set -x
            shift
            ;;
        -v|--verbose)
            verbose=1
            shift
            ;;
        -b|--build_conf)
            build_conf
            exit 0
            ;;
        *)
            break
            ;;
    esac
done

main() {
    ((verbose)) && pi "Running $script"
    build_conf
    # shellcheck disable=SC2068
    exec /usr/bin/i3 $@
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT INT
    main "$@"
fi
