#!/bin/bash
set -euo pipefail

script=$(basename "$0")
srcdir=$(readlink -f "$(dirname "$0")")
readonly LOG_FILE="/tmp/$script.log"
_p() { l=$1; shift; echo "$l $script: $*" | tee -a "$LOG_FILE" >&2; }
pt() { _p "[TRACE]  " "$*";                                         }
pd() { _p "[DEBUG]  " "$*";                                         }
pi() { _p "[INFO]   " "$*";                                         }
pw() { _p "[WARNING]" "$*";                                         }
pe() { _p "[ERROR]  " "$*";                                         }
pf() { _p "[FATAL]  " "$*"; exit 1;                                 }

usage() {
    cat <<EOT
$script --help
$script --trace --verbose
$script options
EOT
    exit 0
}

cleanup() {
    declare -r res=$?
    ((verbose)) && pi "Cleaning up"
    exit $res
}

PATH="$srcdir:$PATH"
verbose=0

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            shift
            ;;
        -t|--trace)
            set -x
            shift
            ;;
        -v|--verbose)
            verbose=1
            shift
            ;;
        *)
            break
            ;;
    esac
done

main() {
    PATH=~/g/base/utils:~/g/sw/bin:$PATH
    hostname=$(hostname)
    ((verbose)) && pi "Running on $hostname"

    xrdb -merge .Xdefaults
    xsetroot -bg black
    clipit -d &
    gnome-panel &
    [ "$ISVM" ] || sudo nice -n -20 ~/g/sw/bin/caps2esc \
        >| ~/caps2esc.log 2>| ~/caps2esc.err &

    case "$hostname" in
        caub1)
            slack &
            ;;
        pj)
            xrandr --output HDMI-3 --left-of LVDS-1
            slack &
            ;;
        posub64)
            xmodmap -e "pointer = 1 3 2"
            numlockx on
            ;;
        *)
            pi "Unknown host: $hostname"
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT INT
    main "$@"
fi


# xrdb -merge .Xdefaults
# xrandr --output HDMI-3 --left-of LVDS-1
# xsetroot -bg black
# xmodmap -e "pointer = 1 3 2"
# numlockx on
# clipit -d &
# gnome-panel &
# slack &
# [ "$ISVM" ] || sudo nice -n -20 ~/g/sw/bin/caps2esc >| ~/caps2esc.log 2>| ~/caps2esc.err &


# indicator-keylock &
# (
    # hostname=$(hostname)
    # do_sleep() { sleep 0.25; }

    # do_sleep
    # gnome-panel &
    # clipit -d &
    # sudo nm-applet &

    # confdir=~/g/base/.config/bspwm
    # [ -e "$confdir/layout.$hostname" ] && bspc wm -l "$confdir/layout.$hostname"
    # # shellcheck disable=SC1090
    # [ -e "$confdir/rules.$hostname" ] && . "$confdir/rules.$hostname"
    # if [ "$hostname" = "pj" ]; then
        # rm -rf "$HOME"/.ssh/tmp/*
        # firefox &
        # thunderbird &
        # st -s 12 &
        # do_sleep
        # st -s 10 ssh h &
        # sleep 3
        # st -s 10 ssh pjcj.net &
        # do_sleep
        # st -s 14 &
        # do_sleep
        # st -s 10 &
        # do_sleep
        # st -s 14 irssi &
    # elif [ "$hostname" = "posub64" ]; then
        # firefox &
        # st -s 16 &
        # do_sleep
        # st -s 16 ssh pjcj.net &
        # do_sleep
        # st -s 16 &
        # do_sleep
        # st -s 14 ssh cp1 &
        # do_sleep
        # st -s 14 &
        # do_sleep
        # st -s 14 &
        # do_sleep
        # st -s 14 &
        # do_sleep
        # st -s 14 &
    # fi
# ) &
