#!/bin/sh

if [ -t 1 ]; then
    if [ $(uname) = Linux ]; then
        eval $(dircolors -b ~/g/base/dircolours)
    elif [ $(uname) = Darwin ]; then
        eval $(gdircolors -b ~/g/base/dircolours)
        [[ -e /usr/local/bin/gls ]] && exec /usr/local/bin/gls "$@"
        exec /opt/homebrew/opt/coreutils/libexec/gnubin/ls "$@"
    fi
fi

exec /bin/ls "$@"
