#!/bin/sh

# create new tmux terminfo entries with italics

cat <<EOF|tic -x -
tmux|tmux terminal multiplexer,
        ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
        use=xterm+tmux, use=screen,

tmux-256color|tmux with 256 colors,
        use=st-256color, use=tmux,
EOF
