#!/bin/bash

# Run st (terminal) with Inconsolata font and specified font size.

set -euo pipefail

# set -x; exec 2> /tmp/st.out

script=$(basename "$0")
scrdir=$(readlink -f "$(dirname "$0")")
readonly LOG_FILE="/tmp/$script.log"
_p() { l=$1; shift; echo "$l $script: $*" | tee -a "$LOG_FILE" >&2; }
pt() { _p "[TRACE]  " "$*";                                         }
pd() { _p "[DEBUG]  " "$*";                                         }
pi() { _p "[INFO]   " "$*";                                         }
pw() { _p "[WARNING]" "$*";                                         }
pe() { _p "[ERROR]  " "$*";                                         }
pf() { _p "[FATAL]  " "$*"; exit 1;                                 }

usage() {
    cat <<EOT
$script --help
$script --trace --verbose
$script options
EOT
    exit 0
}

cleanup() {
    declare -r res=$?
    ((verbose)) && pi "Cleaning up"
    exit $res
}

PATH="$scrdir:$PATH"
verbose=0
size=20

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            shift
            ;;
        -t|--trace)
            set -x
            shift
            ;;
        -v|--verbose)
            verbose=1
            shift
            ;;
        -s|--size)
            size="$2"
            shift 2
            ;;
        *)
            break
            ;;
    esac
done

main() {
    kitty=~/pjcj/.local/kitty.app/bin/kitty
    # we can't use $ISVM from zshrc as it isn't available in the window manager
    [ -e $kitty ] && \
        command -v dmidecode >&/dev/null && \
        (sudo dmidecode -t system | grep -q VirtualBox) && \
        exec $kitty "$@"

    st=~/g/sw/bin/st
    [ -e $st ] && \
        exec $st -f \
            "Inconsolata NF:pixelsize=$size:antialias=false" \
            "$@"

    exec gnome-terminal
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT INT
    main "$@"
fi
