#!/usr/bin/env bash

# Define ANSI color codes for regular colors
BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
MAGENTA="\033[0;35m"
CYAN="\033[0;36m"
WHITE="\033[0;37m"

# Define ANSI color codes for bold colors
BOLD_BLACK="\033[1;30m"
BOLD_RED="\033[1;31m"
BOLD_GREEN="\033[1;32m"
BOLD_YELLOW="\033[1;33m"
BOLD_BLUE="\033[1;34m"
BOLD_MAGENTA="\033[1;35m"
BOLD_CYAN="\033[1;36m"
BOLD_WHITE="\033[1;37m"

NC="\033[0m" # No Color

# Display regular colors
echo -e "${BLACK}Black${NC}"
echo -e "${RED}Red${NC}"
echo -e "${GREEN}Green${NC}"
echo -e "${YELLOW}Yellow${NC}"
echo -e "${BLUE}Blue${NC}"
echo -e "${MAGENTA}Magenta${NC}"
echo -e "${CYAN}Cyan${NC}"
echo -e "${WHITE}White${NC}"

# Display bold colors
echo -e "${BOLD_BLACK}Bold Black${NC}"
echo -e "${BOLD_RED}Bold Red${NC}"
echo -e "${BOLD_GREEN}Bold Green${NC}"
echo -e "${BOLD_YELLOW}Bold Yellow${NC}"
echo -e "${BOLD_BLUE}Bold Blue${NC}"
echo -e "${BOLD_MAGENTA}Bold Magenta${NC}"
echo -e "${BOLD_CYAN}Bold Cyan${NC}"
echo -e "${BOLD_WHITE}Bold White${NC}"
