#!/bin/bash

PATH=~/g/sw/bin:$PATH

xrdb -merge .Xdefaults
xsetroot -bg black
numlockx on
gnome-settings-daemon --replace > /dev/null 2>&1 &
[ "$ISVM" ] || sudo nice -n -20 caps2esc >|caps2esc.log 2>|caps2esc.err &
indicator-keylock &
(
    hostname=$(hostname)
    do_sleep() { sleep 0.25; }

    do_sleep
    gnome-panel &
    clipit -d &
    sudo nm-applet &

    confdir=~/g/base/.config/bspwm
    [ -e "$confdir/layout.$hostname" ] && bspc wm -l "$confdir/layout.$hostname"
    # shellcheck disable=SC1090
    [ -e "$confdir/rules.$hostname" ] && . "$confdir/rules.$hostname"
    if [ "$hostname" = "pj" ]; then
        firefox &
        thunderbird &
        st irssi &
        do_sleep
        st &
        do_sleep
        st ssh h.pjcj.net &
        do_sleep
        st ssh h.pjcj.net &
        do_sleep
        st &
    elif [ "$hostname" = "posub64" ]; then
        firefox &
        st16 &
        do_sleep
        st16 ssh am1 &
        do_sleep
        st18 &
        do_sleep
        st14 ssh cp1 &
        do_sleep
        st16 &
        do_sleep
        st16 &
        do_sleep
        st14 &
    fi
) &
