#!/bin/sh

PATH=/home/pjcj/g/sw/bin:$PATH

xrdb -merge .Xdefaults
xsetroot -bg black
numlockx on
gnome-settings-daemon --replace > /dev/null 2>&1 &
sudo nice -n -20 =caps2esc >|caps2esc.log 2>|caps2esc.err &
indicator-keylock &
(
    sleep 1
    gnome-panel &
    clipit -d &
    st &
    sudo nm-applet &
    if [ "$(hostname)" = "pj" ]; then
        thunderbird &
        firefox &
        st irssi &
    fi
) &
