#!/bin/sh

bspc config border_width                                        2
bspc config window_gap                                          0
bspc config -m $(bspc query -M | awk "NR == 1") bottom_padding  24
bspc config split_ratio                                         0.45
bspc config borderless_monocle                                  true
bspc config gapless_monocle                                     true
bspc config focus_by_distance                                   true
bspc config focus_follows_pointer                               true
bspc config remove_disabled_monitors                            true
bspc config remove_unplugged_monitors                           true

bspc config focused_border_color                                "#6c71c4"
bspc config normal_border_color                                 "#022731"

if [ $(hostname) = "pj" ]; then
    bspc monitor LVDS1 -d I II III
    bspc monitor HDMI2 -d 1 2 3
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Firefox     desktop=II
bspc rule -a Thunderbird desktop=II
bspc rule -a JDownloader desktop=IV

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
