#!/bin/sh

bspc config border_width            1
bspc config window_gap              0
bspc config bottom_padding          24
bspc config split_ratio             0.45
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config focus_follows_pointer   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Firefox     desktop=II
bspc rule -a JDownloader desktop=IV

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
